config/routes.rb
Rails.application.routes.draw do

   devise_for :users,
    controllers: {
       registrations: :registrations,
      },
    path_names: {
      password: 'forgot',
      registration: 'register',
      sign_up: 'signup'
    }
    
  as :user do  
    get '/login', to: 'devise/sessions#new' 
    post 'login', to: 'devise/sessions#new' 
    get '/sign_up', to: 'registrations#new'
    get '/edit_profile', to: "devise/registrations#edit"
    get "/forgot/new", to: "devise/passwords#new"
  end  
  
  namespace :admin do
    resources :administrators, :news, :tags, :questions
    resources :birth_plans do
      get "assign_ques", on: :collection
      post "assign_ques", on: :collection
      patch "assign_ques", on: :collection
      post :sort, on: :collection
      get :get_question, on: :member
      post :get_question, on: :member
      get "restrict", on: :collection
      post "reset", on: :collection
      post "restrict", on: :collection
    end  

    resources :users do 
      get 'birth_plan_report', on: :member
      post 'birth_plan_report', on: :member
    end

    resources :password_resets
    resources :sessions, only: [ :new, :create, :destroy]
    resources :team_members do
      post :sort, on: :collection
    end

    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    #post '/admin/birth_plans/reset' => 'birth_plans#reset'

    root to: 'news#index'
  end

  %w( facts what framework solutions culture policy video team projects ).each do |page|
    get "/#{page}" => "public##{page}", as: page.to_sym
  end

  resources :news, only: [ :show, :index ]
  resources :tags, only: :show
  resources :birth_plans do
    get 'index', to: 'birth_plans#index'
    get 'active_plan', on: :collection
    post 'answer', on: :member
  end  
  
  get '/get_restriction', to: 'birth_plan_answers#get_restriction'
  get "edit_questions" => "birth_plan_answers#edit"

  resources :birth_plan_answers, :path => 'questions' do
    get :report, on: :collection
  end  
  
  root to: 'public#video'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  #attr_accessor :name, :email, :password, :password_confirmation, :reset_token, :resent_sent_at
  # Gems
  has_secure_password

  # Validations
  #validates :name, :email, presence: true, :allow_blank => true
  #validates :email, email: true, :allow_blank => true
  validates_uniqueness_of :name
  validates :password, confirmation: true

  before_create { generate_token(:auth_token) }

  

	def send_password_reset
	  generate_token(:reset_token)
	  self[:resent_sent_at] = Time.now
	  save!
	  AdminMailer.password_reset(self).deliver_now
	end



  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Administrator.exists?(column => self[column])
  end

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController

  before_action :get_admin, only: [ :edit, :update, :destroy ]

  def new
    @administrator = Administrator.new
  end

  def create
    @administrator = Administrator.new(admin_params)
    if @administrator.save
      flash[:success] = 'Administrator created successfully.'
      redirect_to admin_administrators_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @administrator.update(admin_params)
      flash[:success] = 'Administrator updated.'
      redirect_to admin_administrators_path
    else
      render :edit
    end
  end

  def destroy
    @administrator.destroy
    flash[:success] = 'Administrator destroyed.'
    redirect_to admin_administrators_path
  end

  def index
    @administrators = Administrator.order('name asc')
    puts "#{@administrators.inspect}"
  end




  def get_admin
    @administrator = Administrator.find(params[:id])
  end

  def admin_params
    params.require(:administrator).permit(:name, :email, :password, :password_confirmation, :resent_sent_at, :reset_token)
  end

end

app/views/admin/administrators/_form.html.haml
= simple_form_for [ :admin, @administrator ] do |f|
  .row
    .columns.small-12.medium-6
      = f.input :name
      = f.input :password, required: true
    .columns.small-12.medium-6
      = f.input :email
      = f.input :password_confirmation, required: true
      = f.button :button, :class => 'button radius pull-right'

app/views/admin/administrators/edit.html.haml
.row
  .columns.small-12
    %h2 Edit Administrator

= render 'form'

app/views/admin/administrators/index.html.haml
.row
  .columns.small-12
    = link_to 'New', new_admin_administrator_path, :class => 'button radius pull-right secondary'
    %h2 Administrators

    %table
      %thead
        %tr
          %th Name
          %th Email
          %th{ width: '20%' }

      %tbody
        - @administrators.each do |admin|
          %tr
            %td= admin[:name]
            %td= admin[:email]
            %td.actions
              = link_to 'Edit', edit_admin_administrator_path(admin)
              - unless admin.super_admin?
                = link_to 'Delete', admin_administrator_path(admin), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/administrators/new.html.haml
.row
  .columns.small-12
    %h2 New Administrator

= render 'form'