config/routes.rb
Rails.application.routes.draw do

   devise_for :users,
    controllers: {
       registrations: :registrations,
      },
    path_names: {
      password: 'forgot',
      registration: 'register',
      sign_up: 'signup'
    }
    
  as :user do  
    get '/login', to: 'devise/sessions#new' 
    post 'login', to: 'devise/sessions#new' 
    get '/sign_up', to: 'registrations#new'
    get '/edit_profile', to: "devise/registrations#edit"
    get "/forgot/new", to: "devise/passwords#new"
  end  
  
  namespace :admin do
    resources :administrators, :news, :tags, :questions
    resources :birth_plans do
      get "assign_ques", on: :collection
      post "assign_ques", on: :collection
      patch "assign_ques", on: :collection
      post :sort, on: :collection
      get :get_question, on: :member
      post :get_question, on: :member
      get "restrict", on: :collection
      post "reset", on: :collection
      post "restrict", on: :collection
    end  

    resources :users do 
      get 'birth_plan_report', on: :member
      post 'birth_plan_report', on: :member
    end

    resources :password_resets
    resources :sessions, only: [ :new, :create, :destroy]
    resources :team_members do
      post :sort, on: :collection
    end

    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    #post '/admin/birth_plans/reset' => 'birth_plans#reset'

    root to: 'news#index'
  end

  %w( facts what framework solutions culture policy video team projects ).each do |page|
    get "/#{page}" => "public##{page}", as: page.to_sym
  end

  resources :news, only: [ :show, :index ]
  resources :tags, only: :show
  resources :birth_plans do
    get 'index', to: 'birth_plans#index'
    get 'active_plan', on: :collection
    post 'answer', on: :member
  end  
  
  get '/get_restriction', to: 'birth_plan_answers#get_restriction'
  get "edit_questions" => "birth_plan_answers#edit"

  resources :birth_plan_answers, :path => 'questions' do
    get :report, on: :collection
  end  
  
  root to: 'public#video'

end

app/views/shared/_admin_header.html.erb
<header class="default admin">
  <div class="logo">
    <%= link_to image_tag('logo.png', width: 99, height: 56), admin_root_path %>
  </div>
  <div class="menu">
    <ul>
      <% if current_admin %>
        <li>
          <%= link_to 'News', admin_news_index_path %>
        </li>
        <li>
          <%= link_to 'Team', admin_team_members_path %>
        </li>
        <li>
          <%= link_to 'Tags', admin_tags_path %>
        </li>
        <li>
          <%= link_to 'Birth Plan', admin_birth_plans_path %>       
        </li>
        <li>
          <%= link_to 'Admins', admin_administrators_path %>
        </li>
        <li>
          <%= link_to 'Users', admin_users_path %>
        </li>
        <li>
          <%= link_to 'Logout', admin_logout_path %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="clear"></div>
</header>
<style>
header.default .menu ul li a {
  line-height: 25px!important;
}
.dropbtn {
    background-color: #4CAF50;
    color: white;
    padding: 16px;
    font-size: 16px;
    border: none;
    cursor: pointer;
}

.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}

.dropdown-content a {
    color: black;
    padding: 5px 5px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
</style>

app/views/shared/_devise_header.html.erb
<aside class="right-off-canvas-menu">
  <div class="title">Menu</div>
  <ul>
    <li>
      <%= link_to 'Play Video', '#', class: 'play-video' %>
    </li>
    <li>
      <%= link_to 'What We Do', what_path %>
    </li>
    <li>
      <%= link_to 'The Facts', facts_path %>
    </li>
    <!-- %li
    -->
    <!--   = link_to 'Framework:', framework_path
    -->
    <!--   %ul
    -->
    <!--     %li= link_to 'Science', framework_path
    -->
    <!--     %li= link_to 'Solutions', solutions_path
    -->
    <!--     %li= link_to 'Culture', culture_path
    -->
    <li>
      <%= link_to 'Birth Plan', birth_plans_path %>
    </li>
    <li>
      <%= link_to 'Team', team_path %>
    </li>
    <li>
      <%= link_to 'News', news_index_path %>
    </li>
    <li>
      <%= mail_to 'info@squareroots.com', 'Contact Us', :class => 'last', target: '_blank' %>
    </li>
  </ul>
</aside>
<header class="default">
  <div class="logo show-for-large-up">
    <%= link_to image_tag('logo.png', width: 99, height: 56), video_path %>
  </div>
  <div class="logo hide-for-large-up">
    <%= link_to image_tag('logo.png', width: 99, height: 56), what_path %>
  </div>
  <div class="menu">
    <ul>
      <li>
        <%= link_to_unless_current 'Play Video', '#', class: 'play-video' do %>
          <span>Play Video</span>
        <% end %>
      </li>
      <li>
        <%= link_to_unless_current 'What We Do', what_path do %>
          <span>What We Do</span>
        <% end %>
      </li>
      <li>
        <%= link_to_unless_current 'The Facts', facts_path do %>
          <span>The Facts</span>
        <% end %>
      </li>
      <!-- %li
      -->
      <!--   = link_to_unless_current 'Framework', framework_path do
      -->
      <li>
        <%= link_to_unless_current 'Birth Plan', birth_plans_path do %>
          <span>Birth Plan</span>
        <% end %>
      </li>
      
      <li>
        <%= link_to_unless_current 'Team', team_path do %>
          <span>Team</span>
        <% end %>
      </li>
      <li>
        <%= link_to_unless_current 'News', news_index_path do %>
          <span>News</span>
        <% end %>
      </li>
      <li>
        <%= mail_to 'info@squareroots.com', 'Contact Us', :class => 'last', target: '_blank' %>
      </li>
    </ul>
  </div>
  <div class="clear"></div>
</header>
<header class="mobile">
  <%= link_to image_tag('logo.png', width: 70, height: 40), root_path %>
  <%= link_to '#', :class => 'right-off-canvas-toggle' do %>
    <span>MENU</span>
    <i class="icon-menu"></i>
  <% end %>
  <div class="clear"></div>
</header>

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  .alert-box.radius{ :class => key }= value

app/views/shared/_footer.html.haml
%footer
  .mainfooter
    .tagline
      %span The mission of Square Roots&trade; is to define and empower healthy birth.
    .footer-buttons
      = link_to 'Play Video', '#', :class => 'play-video'
      = link_to 'Play Video', '#', :class => 'play-video-direct'
      = mail_to 'info@squareroots.com', 'Contact Us', target: '_blank'

.video-popup.reveal-modal{ data: { reveal: true } }
  .inner
    .close-modal.show-for-small= image_tag 'close.png', width: 27, height: 27
    .clear
    %video{ controls: 'controls', id: 'video', poster: image_path('video.jpg') }
      %source{ src: '/video2.mp4', type: "video/mp4" }
      %source{ src: '/video2.webm', type: "video/webm" }
      %source{ src: '/video2.ogv', type: "video/ogg" }

/ Login Modal
#loginModal.loginModalmodal.modal.fade{:role => "dialog"}
  .modal-dialog{ :style => "width: 60%"}
    / Modal content
    .modal-content
      %button.close{"data-dismiss" => "modal", :type => "button"} × 
      .modal-body
        .form-inputs.main_form_box_l
          %h2.form_head Log in
          = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
            .one-full
              = f.input :email, required: true, autofocus: true, label: false, placeholder: 'Email'
            .one-full
              = f.input :password, required: true, label: false, placeholder: 'Password'
            .one-full
              %span.term_class.squaredThree1
                = f.check_box :remember_me, :id => "squaredThree1", :class => "input_box1"
                %label{:for => "squaredThree1"}
                Remember me?
            .form-actions
              = f.button :submit, "Log in"
            .one-full
              %p
                %a{"data-target" => "#signupModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} SIGN UP
                %a{"data-target" => "#fgModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} FORGET PASSWORD    
                %a{"data-target" => "#recoverModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} RESEND CONFIRMATION INSTRUCTION

/ Signup Modal
#signupModal.modal.signupModalmodal.fade{:role => "dialog"}
  .modal-dialog{ :style => "width: 60%"}
    / Modal content
    .modal-content
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      .modal-body
        .form-inputs.main_form_box
          %h2.form_head SIGN UP NOW
          = simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
            = f.error_notification
            .mr_btm
              .one-half
                = f.input :first_name, required: true, label: false, placeholder: 'First Name', :input_html => {:class => "input_box1" }
              .one-half
                = f.input :last_name, required: true, label: false, placeholder: 'Last Name', :input_html => {:class => "input_box2" }
            .one-full
              = f.input :email, required: true, label: false, placeholder: 'Email', :input_html => {:class => "input_box3" }
            .one-half
              = f.input :password, required: true, label: false , placeholder: 'Password', :input_html => {:class => "input_box4" }
            .one-half
              = f.input :password_confirmation, required: true, label: false, placeholder: 'Confirm Password', :input_html => {:class => "input_box5" }
            .one-half
              = f.input :zipcode, required: true, label: false, placeholder: 'Zip code', :input_html => {:class => "input_box6" }, as: :string 
            .one-half
              = f.input :due_date, required: true, label: false, placeholder: 'Due Date', :input_html => {:class => "due_date input_box7 datepicker" }, as: :string 
            .one-full
              %span.term_class.squaredThree
                = f.check_box :terms_n_condition, id: "squaredThree"
                %label{:for => "squaredThree"}
                I agree to the Terms of use and Privacy Statement                
            .form-actions
              = f.button :submit, "Sign up"
            .one-full
              %p
                Have an Account?
                %a{"data-target" => "#loginModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"}LOG IN

/ forget password Modal
#fgModal.modal.fade{:role => "dialog"}
  .modal-dialog{ :style => "width: 60%"}
    / Modal content
    .modal-content
      %button.close{"data-dismiss" => "modal", :type => "button"} × 
      .modal-body
        .form-inputs.main_form_box
          %h2.form_head Forgot your password?
          = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f|
            = f.error_notification
            = f.input :email, required: true, autofocus: true, label:false, placeholder:"Email"
            .form-actions
              = f.button :submit, "Send me reset password instructions"
            .one-full
              %p
                %a{"data-target" => "#loginModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"}LOG IN
                %a{"data-target" => "#signupModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} SIGN UP   
                %a{"data-target" => "#recoverModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} RESEND CONFIRMATION INSTRUCTION


/ Resend confirmation instructions Modal
#recoverModal.modal.fade{:role => "dialog"}
  .modal-dialog{ :style => "width: 60%"}
    / Modal content
    .modal-content
      %button.close{"data-dismiss" => "modal", :type => "button"} × 
      .modal-body
        .form-inputs.main_form_box
          %h2.form_head Resend confirmation instructions
          = simple_form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f|
            = f.error_notification
            = f.full_error :confirmation_token
            = f.input :email, required: true, autofocus: true,label:false, placeholder:"Email"
            %div
              = f.button :submit, "Resend confirmation instructions"
            .one-full
              %p
                %a{"data-target" => "#loginModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"}LOG IN
                %a{"data-target" => "#signupModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} SIGN UP   
                %a{"data-target" => "#fgModal", :type => "button", :style => "color: #f4c553;margin-left: 10px;", :class => "cls_modal"} FORGET PASSWORD

app/views/shared/_footer1.html.erb
<footer>
  <div class="mainfooter">
    <div class="tagline">
      <span>The mission of Square Roots&trade; is to define and empower healthy birth.</span>
    </div>
    <div class="footer-buttons">
      <%= link_to 'Play Video', '#', :class => 'play-video' %>
      <%= link_to 'Play Video', '#', :class => 'play-video-direct' %>
      <%= mail_to 'info@squareroots.com', 'Contact Us', target: '_blank' %>
    </div>
  </div>
</footer>
<div class="video-popup reveal-modal" data-reveal>
  <div class="inner">
    <div class="close-modal show-for-small">
      <%= image_tag 'close.png', width: 27, height: 27 %>
    </div>
    <div class="clear"></div>
    <video controls="controls" id="video" poster="<%= image_path('video.jpg') %>">
      <source src="/video2.mp4" type="video/mp4"></source>
      <source src="/video2.webm" type="video/webm"></source>
      <source src="/video2.ogv" type="video/ogg"></source>
    </video>
  </div>
</div>

app/views/shared/_header.html.haml
%aside.right-off-canvas-menu
  .title Menu
  %ul
    %li= link_to 'Play Video', '#', class: 'play-video'
    %li= link_to 'What We Do', what_path
    %li= link_to 'The Facts', facts_path
    / %li
    /   = link_to 'Framework:', framework_path
    /   %ul
    /     %li= link_to 'Science', framework_path
    /     %li= link_to 'Solutions', solutions_path
    /     %li= link_to 'Culture', culture_path
    %li= link_to 'Birth Plan', birth_plans_path
    %li= link_to 'Team', team_path
    %li= link_to 'News', news_index_path
    / %li= link_to 'Projects', projects_path
    %li= mail_to 'info@squareroots.com', 'Contact Us', :class => 'last', target: '_blank'

%header.default
  .logo.show-for-large-up= link_to image_tag('logo.png', width: 99, height: 56), video_path
  .logo.hide-for-large-up= link_to image_tag('logo.png', width: 99, height: 56), what_path
  .menu
    %ul
      %li
        = link_to_unless_current 'Play Video', '#', class: 'play-video' do
          %span Play Video
      %li
        = link_to_unless_current 'What We Do', what_path do
          %span What We Do
      %li
        = link_to_unless_current 'The Facts', facts_path do
          %span The Facts
      %li
        = link_to_unless_current 'Birth PLan', birth_plans_path do
          %span Birth Plan
      %li
        = link_to_unless_current 'Team', team_path do
          %span Team
      %li
        = link_to_unless_current 'News', news_index_path do
          %span News
      %li
        = mail_to 'info@squareroots.com', 'Contact Us', :class => 'last', target: '_blank'
  .clear

%header.mobile
  = link_to image_tag('logo.png', width: 70, height: 40), root_path
  = link_to '#', :class => 'right-off-canvas-toggle' do
    %span MENU
    %i.icon-menu
  .clear

.splash{ data: { imgliquid: true } }
  - unless content_for(:no_splash)
    = image_tag "#{action_name}-splash.jpg"

.row
  - if notice
    %p.alert.alert-success= notice
  - if alert
    %p.alert.alert-danger= alert
  - if user_signed_in?
    Logged in as
    = succeed "." do
      %strong= current_user.email
    = link_to 'Edit profile', edit_profile_path, :class => 'navbar-link'
    |
    \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
  - else
    |

.row
  .columns.small-12

    - unless content_for(:no_title)
      .title
        %h1= title

    .quote
      .open= image_tag 'quote-open.jpg', width: 50, height: 30
      %blockquote
        = t("quotes.#{action_name}.quote")
        %cite= t("quotes.#{action_name}.cite")
.close= image_tag 'quote-close.jpg', width: 50, height: 30

app/views/shared/_pdf_footer.html.erb
<footer>
  <div class="mainfooter">
    <div class="tagline">
      <span>The mission of Square Roots&trade; is to define and empower healthy birth.</span>
    </div>
  </div>
</footer>

app/views/shared/_pdf_header.html.erb
<header class="default">
  <div class="logo show-for-large-up">
   <%= wicked_pdf_image_tag('pdf_log.png') %>
  </div>
</header> 

app/views/shared/_signup.html.erb
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>