config/routes.rb
Rails.application.routes.draw do

   devise_for :users,
    controllers: {
       registrations: :registrations,
      },
    path_names: {
      password: 'forgot',
      registration: 'register',
      sign_up: 'signup'
    }
    
  as :user do  
    get '/login', to: 'devise/sessions#new' 
    post 'login', to: 'devise/sessions#new' 
    get '/sign_up', to: 'registrations#new'
    get '/edit_profile', to: "devise/registrations#edit"
    get "/forgot/new", to: "devise/passwords#new"
  end  
  
  namespace :admin do
    resources :administrators, :news, :tags, :questions
    resources :birth_plans do
      get "assign_ques", on: :collection
      post "assign_ques", on: :collection
      patch "assign_ques", on: :collection
      post :sort, on: :collection
      get :get_question, on: :member
      post :get_question, on: :member
      get "restrict", on: :collection
      post "reset", on: :collection
      post "restrict", on: :collection
    end  

    resources :users do 
      get 'birth_plan_report', on: :member
      post 'birth_plan_report', on: :member
    end

    resources :password_resets
    resources :sessions, only: [ :new, :create, :destroy]
    resources :team_members do
      post :sort, on: :collection
    end

    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    #post '/admin/birth_plans/reset' => 'birth_plans#reset'

    root to: 'news#index'
  end

  %w( facts what framework solutions culture policy video team projects ).each do |page|
    get "/#{page}" => "public##{page}", as: page.to_sym
  end

  resources :news, only: [ :show, :index ]
  resources :tags, only: :show
  resources :birth_plans do
    get 'index', to: 'birth_plans#index'
    get 'active_plan', on: :collection
    post 'answer', on: :member
  end  
  
  get '/get_restriction', to: 'birth_plan_answers#get_restriction'
  get "edit_questions" => "birth_plan_answers#edit"

  resources :birth_plan_answers, :path => 'questions' do
    get :report, on: :collection
  end  
  
  root to: 'public#video'

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  self.per_page = 10

  # Gems
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Associations
  has_many :news, dependent: :nullify

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController

  before_action :get_tag, only: [ :edit, :update, :destroy ]

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = 'Tag created successfully.'
      redirect_to admin_tags_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      flash[:success] = 'Tag updated.'
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    flash[:success] = 'Tag destroyed.'
    redirect_to admin_tags_path
  end

  def index
    @tags = Tag.order('name asc').paginate(:page => params[:page])
  end


  private

  def get_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag   = Tag.find(params[:id])
    @posts = @tag.news.order('post_date desc')
    render 'news/index'
  end

end

app/views/admin/tags/_form.html.haml
= simple_form_for [ :admin, @tag ] do |f|
  .row
    .columns.small-12.medium-6
      = f.input :name
      = f.button :button, :class => 'button radius pull-right'
    .columns.small-12.medium-6

app/views/admin/tags/edit.html.haml
.row
  .columns.small-12
    %h2 Edit Tag

= render 'form'

app/views/admin/tags/index.html.haml
.row
  .columns.small-12
    = link_to 'New', new_admin_tag_path, :class => 'button radius pull-right secondary'
    %h2 Tags

    %table
      %thead
        %tr
          %th Name
          %th{ width: '20%' }

      %tbody
        - @tags.each do |tag|
          %tr
            %td= tag.name
            %td.actions
              = link_to 'Edit', edit_admin_tag_path(tag)
              = link_to 'Delete', admin_tag_path(tag), method: :delete, data: { confirm: 'Are you sure?' }
        %tr
          %td= will_paginate @tags

app/views/admin/tags/new.html.haml
.row
  .columns.small-12
    %h2 New Tag

= render 'form'