config/routes.rb
Rails.application.routes.draw do

   devise_for :users,
    controllers: {
       registrations: :registrations,
      },
    path_names: {
      password: 'forgot',
      registration: 'register',
      sign_up: 'signup'
    }
    
  as :user do  
    get '/login', to: 'devise/sessions#new' 
    post 'login', to: 'devise/sessions#new' 
    get '/sign_up', to: 'registrations#new'
    get '/edit_profile', to: "devise/registrations#edit"
    get "/forgot/new", to: "devise/passwords#new"
  end  
  
  namespace :admin do
    resources :administrators, :news, :tags, :questions
    resources :birth_plans do
      get "assign_ques", on: :collection
      post "assign_ques", on: :collection
      patch "assign_ques", on: :collection
      post :sort, on: :collection
      get :get_question, on: :member
      post :get_question, on: :member
      get "restrict", on: :collection
      post "reset", on: :collection
      post "restrict", on: :collection
    end  

    resources :users do 
      get 'birth_plan_report', on: :member
      post 'birth_plan_report', on: :member
    end

    resources :password_resets
    resources :sessions, only: [ :new, :create, :destroy]
    resources :team_members do
      post :sort, on: :collection
    end

    get '/login'  => 'sessions#new'
    get '/logout' => 'sessions#destroy'
    #post '/admin/birth_plans/reset' => 'birth_plans#reset'

    root to: 'news#index'
  end

  %w( facts what framework solutions culture policy video team projects ).each do |page|
    get "/#{page}" => "public##{page}", as: page.to_sym
  end

  resources :news, only: [ :show, :index ]
  resources :tags, only: :show
  resources :birth_plans do
    get 'index', to: 'birth_plans#index'
    get 'active_plan', on: :collection
    post 'answer', on: :member
  end  
  
  get '/get_restriction', to: 'birth_plan_answers#get_restriction'
  get "edit_questions" => "birth_plan_answers#edit"

  resources :birth_plan_answers, :path => 'questions' do
    get :report, on: :collection
  end  
  
  root to: 'public#video'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  #validates_presence_of :email, :password

  self.per_page = 10
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end 

  def delete
    @user = User.find(params[:id])
    @user.delete
    redirect_to admin_users_path
  end  

  def birth_plan_report
    @user = User.find(params[:id])
    @answers = BirthPlanAnswer.where("user_id = ?", @user.id)
    
    @questions = []
    questions = @answers.pluck(:question_id).uniq 

    questions.each do |ques|
      begin
        @questions <<  Question.find(ques)
      rescue Exception => e
        logger.error e.message    
        next
      end
    end   
  end  

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  layout 'devise'

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'devise'


  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'devise'

# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  #def new
  #   puts "+++++++++++++++++++++++++++++++++++++++++++++"    
  #  super
  #end

  # POST /resource
  #def create
  #  puts "+++++++++++++++++++++++++++++++++++++++++++++"
  #  super
  #  redirect_to birth_plans_path
  #  puts "------------------------------------------------"
  #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  #def update
  #  super
  #  edit_profile_path
  #end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    birth_plans_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource) 
        birth_plans_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'devise'

# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  layout 'devise'

  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/birth_plan_report.html.erb
<div class="row">
	<h2><%= @user.first_name %> Report</h2>
 
	<table>
  	<% @questions.each_with_index do |ques, ind| %>
	    <tr>
        <td>Question<%= ind+1 %>.&nbsp&nbsp<%=link_to ques.title %>
        </td>
      </tr>
      <tr>
        <td>
          <% answers = @answers.where(question_id: ques) %>
          <% answers.each do |answer| %>
            Answer.&nbsp&nbsp <%= answer.answer %><br>
          <% end %>
          <hr>
        </td>
      </tr>    
    <% end %>    
  </table>
</div>

app/views/admin/users/index.html.haml
.row
  .columns.small-12
    /= link_to 'New', new_admin_administrator_path, :class => 'button radius pull-right secondary'
    %h2 Users

    %table
      %thead
        %tr
          %th Name
          %th Email
          %th{ width: '30%' }

      %tbody
        - @users.each do |user|
          %tr
            %td= user.first_name + ' ' +user.last_name
            %td= user.email
            %td.actions
              = link_to 'Birth Plan',birth_plan_report_admin_user_path(user)
              = link_to 'Show', admin_user_path(user)
              = link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }
        %tr
          %td= will_paginate @users

app/views/admin/users/show.html.haml
.row
  .columns.small-12
    %h2= @user.first_name + @user.last_name

    /= link_to 'Edit', edit_admin_team_member_path(@team_member), :class => 'button tiny radius info'
    /= link_to 'Delete', admin_team_member_path(@team_member), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button tiny radius info'

.row
  .col-sm-2
    %strong First Name
  .col-sm-10
    = @user.first_name
.row
  .col-sm-2
    %strong Last Name
  .col-sm-10
    = @user.last_name
.row
  .col-sm-2
    %strong Email
  .col-sm-10
    = @user.email
.row
  .col-sm-2
    %strong Zipcode
  .col-sm-10
    = @user.zipcode || "N/A"
.row
  .col-sm-2
    %strong Due Date
  .col-sm-10
    = @user.due_date || "N/A"